name: Continuous integration

on:
  push:
    paths-ignore:
    - '**.md'
    - '**.ps1'

jobs:
  build_and_test:
    timeout-minutes: 8
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Unit tests
      run: dotnet test --no-restore --no-build --configuration Release
