name: Continuous integration

on: [push]

jobs:
  build_and_test:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.302

    - name: Clean
      run: dotnet clean ./PiwigoScreenSaver.sln --configuration Release && dotnet nuget locals all --clear

    - name: Build
      run: dotnet build --configuration Release

    - name: Unit tests
      run: dotnet test PiwigoScreenSaver.Tests --configuration Release
