name: Continuous integration

on:
  push:
    paths-ignore:
    - '**.md'
    - '**.ps1'

jobs:
  build_and_test:
    name: Build and Test
    timeout-minutes: 8
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Unit tests
        run: dotnet test --no-build --configuration Release
